os:
  - linux
  - windows
language: cpp
compiler:
  - gcc
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install qt5-qmake qtbase5-dev qtdeclarative5-dev qt5-default qttools5-dev-tools
install:
  - make
script:
  - make
