os:
  - linux
  - windows
language: cpp
compiler:
  - gcc
sudo: required
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq 
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev qt5-default qttools5-dev-tools
install:
  - make
script:
  - make
