os:
  - linux
  - windows
language: cpp
compiler:
  - gcc
sudo: required
before_install:
    - sudo apt-get update
    - sudo apt-get install qt5-qmake qtbase5-dev qtdeclarative5-dev
install:
  - make
script:
  - make
