clone_depth: 1

environment:    
  
matrix:
  - platform: Win32 
      QTDIR: C:\Qt\5.4\msvc2013_opengl
  - platform: x64 
      QTDIR: C:\Qt\5.4\msvc2013_x64_opengl
    
before_build:
  - git submodule init lib/serial
  - git submodule update lib/serial

platform:
  - Win32
  - x64
configuration:
  - Debug
  - Release

build:
  project: OpenPST-vs2013.sln
