clone_depth: 1

environment:    
  QTDIR: C:\Qt\5.4\msvc2013_opengl

before_build:
  - git submodule init lib/serial
  - git submodule update lib/serial

platform:
  - Win32

configuration:
  - Debug
  - Release

build:
  project: OpenPST-vs2013.sln