clone_depth: 1

environment:
  QT_DIR: C:\Qt\5.4\msvc2013_64_opengl
  QTDIR: C:\Qt\5.4\msvc2013_64_opengl

before_build:
  - git submodule init
  - git submodule update --depth=1

platform:
  - x86
  - Any CPU

configuration:
  - Debug
  - Release

build:
  project: OpenPST.sln