clone_depth: 1

environment: 
  QTDIR: C:\Qt\5.4\msvc2013

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - git submodule init lib/serial
  - git submodule update lib/serial

build:
  project: OpenPST-vs2013.sln
